
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'app.title': 'ANI GENAI PORTAL',
    'language.toggle': 'PT | EN',
    'user.settings': 'User Settings',
    'help': 'Help',
    'login': 'Login',
    'logout': 'Logout',
    'logout.success': 'Logged out successfully',
    'logout.error': 'Error logging out',
    
    // Navigation
    'main': 'Main',
    'utilities': 'Utilities',
    'settings': 'Settings',
    'funding': 'Funding',
    'projects': 'Projects',
    'analytics': 'Analytics',
    'reports': 'Reports',
    'policies': 'Policies',
    'upload': 'Upload File',
    'link': 'Add Link',
    'category': 'Add Category',
    'home': 'Home',
    'database': 'Database',
    'synthetic_data': 'Synthetic Data',
    
    // Policies
    'policy.search.placeholder': 'Search policies...',
    'policy.notfound': 'No policies found matching your criteria.',
    'policy.category': 'Category',
    'policy.effective': 'Effective',
    'policy.review': 'Review',
    'policy.framework': 'Framework',
    'policy.view': 'View',
    'policy.download': 'PDF',
    'policy.download.title': 'Download Policy PDF',
    'policy.download.description': 'This will download the PDF document for this policy.',
    'policy.download.question': 'Are you sure you want to download the PDF for',
    'policy.download.cancel': 'Cancel',
    'policy.download.confirm': 'Download',
    'policy.download.success': 'Policy PDF downloaded',
    'policy.download.description.success': 'has been downloaded successfully.',
    
    // Policy Page
    'policy.back': 'Back',
    'policy.status': 'Status',
    'policy.details': 'Policy Details',
    'policy.implementation': 'Implementation Guidelines',
    'policy.objectives': 'Objectives',
    'policy.metrics': 'Metrics & Measurements',
    'policies.title': 'Innovation Policies',
    'policies.subtitle': 'Browse and access policy documents and frameworks',
    
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.button': 'Return to Home',
    
    // AuthPage
    'auth.login': 'Login',
    'auth.signup': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loading': 'Loading...',
    'auth.account.create': 'Create Account',
    'auth.account.login': 'Login',
    'auth.account.existing': 'Already have an account? Login',
    'auth.account.need': 'Need an account? Sign Up',
    
    // AddCategory
    'category.title': 'Add Category',
    'category.name': 'Category name',
    'category.description': 'Description (optional)',
    'category.add': 'Add Category',
    'category.cancel': 'Cancel',
    
    // Dashboard tabs
    'dashboard.tab': 'Dashboard',
    'funding.tab': 'Funding',
    'projects.tab': 'Projects',
    'analytics.tab': 'Analytics',
    'reports.tab': 'Reports',
    'policies.tab': 'Policies',
    'assistant.title': 'AI Assistant',
    
    // Index Page
    'index.welcome': 'Welcome to the ANI Innovation Platform',
    'index.choose': 'Choose an option to continue:',
    'index.view.dashboard': 'View Dashboard',
    'index.ai.assistant': 'AI Assistant',
    
    // AddFile Page
    'file.title': 'Add File for AI Analysis',
    'file.select': 'Please select a file',
    'file.upload': 'Upload File',
    'file.uploading': 'Uploading...',
    'file.success': 'File uploaded successfully',
    'file.success.description': 'Your file has been uploaded and is now available for AI analysis.',
    'file.error': 'Error uploading file',
    'file.error.description': 'Please try again later.',
    'file.name': 'Title (optional - will use filename if empty)',
    'file.summary': 'Summary (optional - helps the AI understand the content)',
    'file.category': 'Category (optional - e.g., \'funding\', \'policy\', \'technology\')',
    'file.cancel': 'Cancel',
    
    // AddLink Page
    'link.title': 'Add Link for AI Analysis',
    'link.auth.required': 'Authentication Required',
    'link.auth.description': 'You must be logged in to add links.',
    'link.auth.login': 'Login now',
    'link.loading': 'Loading...',
    'link.name': 'Title',
    'link.url': 'Enter URL',
    'link.summary': 'Summary (helps the AI understand the content)',
    'link.category': 'Category (e.g., \'funding\', \'policy\', \'technology\')',
    'link.add': 'Add Link',
    'link.adding': 'Adding Link...',
    'link.cancel': 'Cancel',
    'link.success': 'Link added successfully',
    'link.error': 'Error adding link',
    'link.fill': 'Please fill in all required fields',
    
    // Analytics Page
    'analytics.title': 'Analytics Dashboard',
    'analytics.search': 'Search analytics...',
    'analytics.filter': 'Filter',
    'analytics.export': 'Export',
    'analytics.export.started': 'Export Initiated',
    'analytics.export.description': 'Your analytics report is being generated.',
    'analytics.tab.funding': 'Funding Analysis',
    'analytics.tab.sectors': 'Sector Analysis',
    'analytics.tab.performance': 'Performance Metrics',
    'analytics.tab.regional': 'Regional Analysis',
    'analytics.tab.predictive': 'Predictive Models',
    'analytics.predictive.title': 'Predictive Innovation Models',
    'analytics.predictive.description': 'AI-powered forecasting of innovation trends and outcomes',
    'analytics.predictive.funding': 'Funding Success Prediction',
    'analytics.predictive.funding.description': 'Our AI model predicts the likelihood of funding success for proposals based on historical data patterns and key success factors.',
    'analytics.predictive.factors': 'Key Success Factors:',
    'analytics.predictive.factor1': 'Strong alignment with national innovation priorities',
    'analytics.predictive.factor2': 'Cross-sector collaboration components',
    'analytics.predictive.factor3': 'Clear commercialization pathway',
    'analytics.predictive.factor4': 'International partnership elements',
    'analytics.predictive.factor5': 'Previous successful project completion',
    'analytics.predictive.trends': 'Innovation Trends Forecast',
    'analytics.predictive.trends.description': 'Forecasting emerging technology trends based on patent data, research publications, and global innovation indicators.',
    'analytics.predictive.confidence': 'confidence',
    'analytics.predictive.simulation': 'Innovation Impact Simulation',
    'analytics.predictive.simulation.description': 'Scenario planning for innovation investments',
    'analytics.predictive.scenario.conservative': 'Conservative Scenario',
    'analytics.predictive.scenario.moderate': 'Moderate Scenario',
    'analytics.predictive.scenario.ambitious': 'Ambitious Scenario',
    'analytics.predictive.metric.jobs': 'Job Creation',
    'analytics.predictive.metric.gdp': 'GDP Impact',
    'analytics.predictive.metric.patents': 'Patent Generation',
    
    // Funding Page
    'funding.title': 'Funding Analytics',
    'funding.export': 'Export Report',
    'funding.download': 'Download Started',
    'funding.download.description': 'The funding report is being downloaded.',
    'funding.tab.overview': 'Overview',
    'funding.tab.programs': 'Programs',
    'funding.tab.sectors': 'Sectors',
    'funding.tab.trends': 'Trends',
    'funding.total': 'Total Funding',
    'funding.active': 'Active Projects',
    'funding.success': 'Success Rate',
    'funding.roi': 'Return on Investment',
    'funding.projects': 'Currently Funded',
    'funding.applications': 'Project Applications',
    'funding.economic': 'Economic Impact',
    'funding.invested': 'For every €1 invested',
    'funding.monthly': 'Monthly Funding Distribution (2023)',
    'funding.by.program': 'Funding by Program',
    'funding.major': 'Major Funding Programs',
    'funding.sources': 'Key innovation funding sources in Portugal',
    'funding.focus': 'Focus: ',
    'funding.how.to': 'How to Apply for Funding',
    'funding.how.description': 'Companies and research institutions can apply for funding through ANI\'s website by following these steps:',
    'funding.step1': 'Identify the appropriate funding program for your project',
    'funding.step2': 'Verify eligibility criteria for the specific call',
    'funding.step3': 'Prepare a project proposal according to the guidelines',
    'funding.step4': 'Submit application through the electronic platform',
    'funding.step5': 'Follow the evaluation process',
    'funding.visit': 'Visit the official ANI website for more details',
    'funding.distribution': 'Funding Distribution by Sector',
    'funding.allocation': '2023 allocation by industry sector',
    'funding.trends': 'Sector Funding Trends',
    'funding.performance': 'Year-over-year sector performance',
    'funding.digital': 'Digital Technologies (+28% YoY)',
    'funding.digital.description': 'Highest growth area with focus on AI, cybersecurity and cloud solutions',
    'funding.energy': 'Clean Energy (+24% YoY)',
    'funding.energy.description': 'Strong growth in renewable technologies and energy efficiency',
    'funding.health': 'Health & Biotech (+18% YoY)',
    'funding.health.description': 'Significant investment in biotechnology and medical devices',
    'funding.manufacturing': 'Advanced Manufacturing (+15% YoY)',
    'funding.manufacturing.description': 'Growth in Industry 4.0 implementations and smart factories',
    'funding.mobility': 'Sustainable Mobility (+12% YoY)',
    'funding.mobility.description': 'Emerging focus on electric vehicles and smart transportation',
    'funding.historical': 'Funding Trends (2018-2023)',
    'funding.all.years': 'All Years',
    'funding.observations': 'Key Observations',
    'funding.observation1': 'Consistent year-over-year funding growth averaging 20% annually',
    'funding.observation2': 'Significant acceleration in funding allocation since 2021 (post-pandemic)',
    'funding.observation3': 'Projected funding for 2024 estimated at €350-380 million',
    'funding.observation4': 'Digital transformation and sustainability projects showing highest growth rates',
    'funding.observation5': 'SMEs receiving increased proportion of funding (up from 42% to 58% since 2020)',
    
    // Framework Page
    'framework.back': 'Back to Policies',
    'framework.period': 'Period: ',
    'framework.download': 'Download',
    'framework.share': 'Share',
    'framework.downloaded': 'Framework document downloaded',
    'framework.downloaded.success': 'has been downloaded successfully.',
    'framework.funding': 'Total Funding',
    'framework.coverage': 'Coverage',
    'framework.tab.overview': 'Overview',
    'framework.tab.funding': 'Funding',
    'framework.tab.governance': 'Governance',
    'framework.tab.performance': 'Performance',
    'framework.description': 'Framework Description',
    'framework.areas': 'Key Focus Areas',
    'framework.objectives': 'Strategic Objectives',
    'framework.allocation': 'Funding Allocation',
    'framework.distribution': 'Distribution of funding across different mechanisms',
    'framework.eligibility': 'Funding Eligibility',
    'framework.research': 'Research Institutions',
    'framework.research.description': 'Universities, research centers, and technology institutes engaged in fundamental or applied research.',
    'framework.companies': 'Private Companies',
    'framework.companies.description': 'SMEs and large enterprises with innovation-focused projects and R&D activities.',
    'framework.consortia': 'Public-Private Consortia',
    'framework.consortia.description': 'Collaborative projects involving both public and private entities.',
    'framework.nonprofit': 'Non-Profit Organizations',
    'framework.nonprofit.description': 'NGOs and foundations working on innovation in social and environmental sectors.',
    'framework.governance': 'Governance Structure',
    'framework.implementation': 'Implementation Process',
    'framework.process.strategy': 'Strategy Definition',
    'framework.process.strategy.description': 'Setting priorities and objectives based on national and European innovation strategies.',
    'framework.process.call': 'Call for Proposals',
    'framework.process.call.description': 'Publication of funding opportunities with detailed requirements.',
    'framework.process.evaluation': 'Evaluation & Selection',
    'framework.process.evaluation.description': 'Assessment of proposals by technical panels and expert committees.',
    'framework.process.monitoring': 'Implementation & Monitoring',
    'framework.process.monitoring.description': 'Project execution with regular progress monitoring and reporting.',
    'framework.process.impact': 'Impact Assessment',
    'framework.process.impact.description': 'Evaluation of results against set objectives and KPIs.',
    'framework.kpi': 'Key Performance Indicators',
    'framework.kpi.target': 'Target: ',
    'framework.kpi.baseline': 'Baseline: ',
    'framework.outcomes': 'Expected Outcomes',
    'framework.impact.economic': 'Economic Impact',
    'framework.impact.innovation': 'Innovation Capacity',
    'framework.impact.societal': 'Societal Benefits',
    'framework.impact.economic1': 'GDP growth contribution of 1.5-2%',
    'framework.impact.economic2': 'Creation of 50,000+ high-skilled jobs',
    'framework.impact.economic3': 'Increased export competitiveness',
    'framework.impact.innovation1': 'Expanded R&D infrastructure',
    'framework.impact.innovation2': 'Enhanced technology transfer',
    'framework.impact.innovation3': 'Growth in patent applications',
    'framework.impact.societal1': 'Digital inclusion improvements',
    'framework.impact.societal2': 'Environmental sustainability gains',
    'framework.impact.societal3': 'Enhanced public service delivery',
    'framework.monitoring': 'Monitoring Framework',
    'framework.annual': 'Annual Progress Reports',
    'framework.annual.description': 'Comprehensive annual evaluation against key metrics and targets.',
    'framework.midterm': 'Mid-term Review (2025)',
    'framework.midterm.description': 'Deep analysis of implementation progress and potential strategy adjustments.',
    'framework.final': 'Final Impact Assessment (2030)',
    'framework.final.description': 'Comprehensive evaluation of outcomes, impacts, and lessons learned.',
    
    // Reports
    'reports.scheduled': 'Monthly Funding Overview',
    'reports.scheduled.description': 'Automated monthly report on funding allocation and utilization',
    'reports.frequency': 'Frequency:',
    'reports.next': 'Next generation:',
    'reports.generated': 'Generated at',
    'reports.recipients': 'Recipients:',
    'reports.preview': 'Preview',
    'reports.pause': 'Pause',
    'reports.resume': 'Resume',
    'reports.delete': 'Delete',
    'reports.confirm': 'Confirm',
    'reports.cancel': 'Cancel'
  },
  pt: {
    // Header
    'app.title': 'PORTAL ANI GENAI',
    'language.toggle': 'PT | EN',
    'user.settings': 'Definições de Utilizador',
    'help': 'Ajuda',
    'login': 'Entrar',
    'logout': 'Sair',
    'logout.success': 'Sessão terminada com sucesso',
    'logout.error': 'Erro ao terminar sessão',
    
    // Navigation
    'main': 'Principal',
    'utilities': 'Utilidades',
    'settings': 'Definições',
    'funding': 'Financiamento',
    'projects': 'Projetos',
    'analytics': 'Análises',
    'reports': 'Relatórios',
    'policies': 'Políticas',
    'upload': 'Carregar Ficheiro',
    'link': 'Adicionar Link',
    'category': 'Adicionar Categoria',
    'home': 'Início',
    'database': 'Base de Dados',
    'synthetic_data': 'Dados Sintéticos',
    
    // Policies
    'policy.search.placeholder': 'Pesquisar políticas...',
    'policy.notfound': 'Nenhuma política encontrada que corresponda aos seus critérios.',
    'policy.category': 'Categoria',
    'policy.effective': 'Efetiva',
    'policy.review': 'Revisão',
    'policy.framework': 'Estrutura',
    'policy.view': 'Ver',
    'policy.download': 'PDF',
    'policy.download.title': 'Transferir PDF da Política',
    'policy.download.description': 'Isto irá transferir o documento PDF desta política.',
    'policy.download.question': 'Tem certeza que deseja transferir o PDF para',
    'policy.download.cancel': 'Cancelar',
    'policy.download.confirm': 'Transferir',
    'policy.download.success': 'PDF da Política transferido',
    'policy.download.description.success': 'foi transferido com sucesso.',
    
    // Policy Page
    'policy.back': 'Voltar',
    'policy.status': 'Estado',
    'policy.details': 'Detalhes da Política',
    'policy.implementation': 'Diretrizes de Implementação',
    'policy.objectives': 'Objetivos',
    'policy.metrics': 'Métricas e Medições',
    'policies.title': 'Políticas de Inovação',
    'policies.subtitle': 'Navegue e acesse documentos e estruturas de políticas',
    
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Ops! Página não encontrada',
    'notfound.button': 'Voltar para a Página Inicial',
    
    // AuthPage
    'auth.login': 'Entrar',
    'auth.signup': 'Criar Conta',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.loading': 'Carregando...',
    'auth.account.create': 'Criar Conta',
    'auth.account.login': 'Entrar',
    'auth.account.existing': 'Já tem uma conta? Entre',
    'auth.account.need': 'Precisa de uma conta? Registe-se',
    
    // AddCategory
    'category.title': 'Adicionar Categoria',
    'category.name': 'Nome da categoria',
    'category.description': 'Descrição (opcional)',
    'category.add': 'Adicionar Categoria',
    'category.cancel': 'Cancelar',
    
    // Dashboard tabs
    'dashboard.tab': 'Painel',
    'funding.tab': 'Financiamento',
    'projects.tab': 'Projetos',
    'analytics.tab': 'Análises',
    'reports.tab': 'Relatórios',
    'policies.tab': 'Políticas',
    'assistant.title': 'Assistente IA',
    
    // Index Page
    'index.welcome': 'Bem-vindo à Plataforma de Inovação ANI',
    'index.choose': 'Escolha uma opção para continuar:',
    'index.view.dashboard': 'Ver Painel',
    'index.ai.assistant': 'Assistente IA',
    
    // AddFile Page
    'file.title': 'Adicionar Ficheiro para Análise IA',
    'file.select': 'Por favor selecione um ficheiro',
    'file.upload': 'Carregar Ficheiro',
    'file.uploading': 'A carregar...',
    'file.success': 'Ficheiro carregado com sucesso',
    'file.success.description': 'O seu ficheiro foi carregado e está agora disponível para análise por IA.',
    'file.error': 'Erro ao carregar ficheiro',
    'file.error.description': 'Por favor tente novamente mais tarde.',
    'file.name': 'Título (opcional - usará o nome do ficheiro se vazio)',
    'file.summary': 'Resumo (opcional - ajuda a IA a entender o conteúdo)',
    'file.category': 'Categoria (opcional - ex., \'financiamento\', \'política\', \'tecnologia\')',
    'file.cancel': 'Cancelar',
    
    // AddLink Page
    'link.title': 'Adicionar Link para Análise IA',
    'link.auth.required': 'Autenticação Necessária',
    'link.auth.description': 'Deve estar autenticado para adicionar links.',
    'link.auth.login': 'Entrar agora',
    'link.loading': 'Carregando...',
    'link.name': 'Título',
    'link.url': 'Inserir URL',
    'link.summary': 'Resumo (ajuda a IA a entender o conteúdo)',
    'link.category': 'Categoria (ex., \'financiamento\', \'política\', \'tecnologia\')',
    'link.add': 'Adicionar Link',
    'link.adding': 'Adicionando Link...',
    'link.cancel': 'Cancelar',
    'link.success': 'Link adicionado com sucesso',
    'link.error': 'Erro ao adicionar link',
    'link.fill': 'Por favor preencha todos os campos obrigatórios',
    
    // Analytics Page
    'analytics.title': 'Painel de Análises',
    'analytics.search': 'Pesquisar análises...',
    'analytics.filter': 'Filtrar',
    'analytics.export': 'Exportar',
    'analytics.export.started': 'Exportação Iniciada',
    'analytics.export.description': 'O seu relatório de análises está sendo gerado.',
    'analytics.tab.funding': 'Análise de Financiamento',
    'analytics.tab.sectors': 'Análise Setorial',
    'analytics.tab.performance': 'Métricas de Desempenho',
    'analytics.tab.regional': 'Análise Regional',
    'analytics.tab.predictive': 'Modelos Preditivos',
    'analytics.predictive.title': 'Modelos Preditivos de Inovação',
    'analytics.predictive.description': 'Previsões baseadas em IA de tendências e resultados de inovação',
    'analytics.predictive.funding': 'Previsão de Sucesso de Financiamento',
    'analytics.predictive.funding.description': 'Nosso modelo de IA prevê a probabilidade de sucesso de financiamento para propostas com base em padrões de dados históricos e fatores-chave de sucesso.',
    'analytics.predictive.factors': 'Fatores-Chave de Sucesso:',
    'analytics.predictive.factor1': 'Forte alinhamento com prioridades nacionais de inovação',
    'analytics.predictive.factor2': 'Componentes de colaboração intersectorial',
    'analytics.predictive.factor3': 'Via clara de comercialização',
    'analytics.predictive.factor4': 'Elementos de parceria internacional',
    'analytics.predictive.factor5': 'Conclusão bem-sucedida de projetos anteriores',
    'analytics.predictive.trends': 'Previsão de Tendências de Inovação',
    'analytics.predictive.trends.description': 'Previsão de tendências tecnológicas emergentes com base em dados de patentes, publicações de pesquisa e indicadores globais de inovação.',
    'analytics.predictive.confidence': 'confiança',
    'analytics.predictive.simulation': 'Simulação de Impacto de Inovação',
    'analytics.predictive.simulation.description': 'Planejamento de cenários para investimentos em inovação',
    'analytics.predictive.scenario.conservative': 'Cenário Conservador',
    'analytics.predictive.scenario.moderate': 'Cenário Moderado',
    'analytics.predictive.scenario.ambitious': 'Cenário Ambicioso',
    'analytics.predictive.metric.jobs': 'Criação de Empregos',
    'analytics.predictive.metric.gdp': 'Impacto no PIB',
    'analytics.predictive.metric.patents': 'Geração de Patentes',
    
    // Funding Page
    'funding.title': 'Análise de Financiamento',
    'funding.export': 'Exportar Relatório',
    'funding.download': 'Download Iniciado',
    'funding.download.description': 'O relatório de financiamento está sendo baixado.',
    'funding.tab.overview': 'Visão Geral',
    'funding.tab.programs': 'Programas',
    'funding.tab.sectors': 'Setores',
    'funding.tab.trends': 'Tendências',
    'funding.total': 'Financiamento Total',
    'funding.active': 'Projetos Ativos',
    'funding.success': 'Taxa de Sucesso',
    'funding.roi': 'Retorno sobre Investimento',
    'funding.projects': 'Atualmente Financiados',
    'funding.applications': 'Candidaturas a Projetos',
    'funding.economic': 'Impacto Econômico',
    'funding.invested': 'Para cada €1 investido',
    'funding.monthly': 'Distribuição Mensal de Financiamento (2023)',
    'funding.by.program': 'Financiamento por Programa',
    'funding.major': 'Principais Programas de Financiamento',
    'funding.sources': 'Principais fontes de financiamento de inovação em Portugal',
    'funding.focus': 'Foco: ',
    'funding.how.to': 'Como Solicitar Financiamento',
    'funding.how.description': 'Empresas e instituições de pesquisa podem solicitar financiamento através do site da ANI seguindo estas etapas:',
    'funding.step1': 'Identificar o programa de financiamento apropriado para o seu projeto',
    'funding.step2': 'Verificar os critérios de elegibilidade para a chamada específica',
    'funding.step3': 'Preparar uma proposta de projeto de acordo com as diretrizes',
    'funding.step4': 'Enviar a candidatura através da plataforma eletrônica',
    'funding.step5': 'Acompanhar o processo de avaliação',
    'funding.visit': 'Visite o site oficial da ANI para mais detalhes',
    'funding.distribution': 'Distribuição de Financiamento por Setor',
    'funding.allocation': 'Alocação de 2023 por setor industrial',
    'funding.trends': 'Tendências de Financiamento Setorial',
    'funding.performance': 'Desempenho setorial ano a ano',
    'funding.digital': 'Tecnologias Digitais (+28% YoY)',
    'funding.digital.description': 'Área de maior crescimento com foco em IA, cibersegurança e soluções em nuvem',
    'funding.energy': 'Energia Limpa (+24% YoY)',
    'funding.energy.description': 'Forte crescimento em tecnologias renováveis e eficiência energética',
    'funding.health': 'Saúde e Biotecnologia (+18% YoY)',
    'funding.health.description': 'Investimento significativo em biotecnologia e dispositivos médicos',
    'funding.manufacturing': 'Manufatura Avançada (+15% YoY)',
    'funding.manufacturing.description': 'Crescimento em implementações da Indústria 4.0 e fábricas inteligentes',
    'funding.mobility': 'Mobilidade Sustentável (+12% YoY)',
    'funding.mobility.description': 'Foco emergente em veículos elétricos e transporte inteligente',
    'funding.historical': 'Tendências de Financiamento (2018-2023)',
    'funding.all.years': 'Todos os Anos',
    'funding.observations': 'Observações Principais',
    'funding.observation1': 'Crescimento consistente de financiamento ano após ano, com média de 20% anualmente',
    'funding.observation2': 'Aceleração significativa na alocação de financiamento desde 2021 (pós-pandemia)',
    'funding.observation3': 'Financiamento projetado para 2024 estimado em €350-380 milhões',
    'funding.observation4': 'Projetos de transformação digital e sustentabilidade mostrando as maiores taxas de crescimento',
    'funding.observation5': 'PMEs recebendo proporção aumentada de financiamento (subindo de 42% para 58% desde 2020)',
    
    // Framework Page
    'framework.back': 'Voltar para Políticas',
    'framework.period': 'Período: ',
    'framework.download': 'Baixar',
    'framework.share': 'Compartilhar',
    'framework.downloaded': 'Documento de estrutura baixado',
    'framework.downloaded.success': 'foi baixado com sucesso.',
    'framework.funding': 'Financiamento Total',
    'framework.coverage': 'Cobertura',
    'framework.tab.overview': 'Visão Geral',
    'framework.tab.funding': 'Financiamento',
    'framework.tab.governance': 'Governança',
    'framework.tab.performance': 'Desempenho',
    'framework.description': 'Descrição da Estrutura',
    'framework.areas': 'Áreas de Foco Principais',
    'framework.objectives': 'Objetivos Estratégicos',
    'framework.allocation': 'Alocação de Financiamento',
    'framework.distribution': 'Distribuição de financiamento através de diferentes mecanismos',
    'framework.eligibility': 'Elegibilidade para Financiamento',
    'framework.research': 'Instituições de Pesquisa',
    'framework.research.description': 'Universidades, centros de pesquisa e institutos tecnológicos envolvidos em pesquisa fundamental ou aplicada.',
    'framework.companies': 'Empresas Privadas',
    'framework.companies.description': 'PMEs e grandes empresas com projetos focados em inovação e atividades de P&D.',
    'framework.consortia': 'Consórcios Público-Privados',
    'framework.consortia.description': 'Projetos colaborativos envolvendo entidades públicas e privadas.',
    'framework.nonprofit': 'Organizações Sem Fins Lucrativos',
    'framework.nonprofit.description': 'ONGs e fundações trabalhando em inovação nos setores social e ambiental.',
    'framework.governance': 'Estrutura de Governança',
    'framework.implementation': 'Processo de Implementação',
    'framework.process.strategy': 'Definição de Estratégia',
    'framework.process.strategy.description': 'Estabelecimento de prioridades e objetivos com base em estratégias nacionais e europeias de inovação.',
    'framework.process.call': 'Chamada de Propostas',
    'framework.process.call.description': 'Publicação de oportunidades de financiamento com requisitos detalhados.',
    'framework.process.evaluation': 'Avaliação e Seleção',
    'framework.process.evaluation.description': 'Avaliação de propostas por painéis técnicos e comitês especializados.',
    'framework.process.monitoring': 'Implementação e Monitoramento',
    'framework.process.monitoring.description': 'Execução do projeto com monitoramento e relatórios regulares de progresso.',
    'framework.process.impact': 'Avaliação de Impacto',
    'framework.process.impact.description': 'Avaliação de resultados em relação a objetivos e KPIs estabelecidos.',
    'framework.kpi': 'Indicadores-Chave de Desempenho',
    'framework.kpi.target': 'Meta: ',
    'framework.kpi.baseline': 'Linha de Base: ',
    'framework.outcomes': 'Resultados Esperados',
    'framework.impact.economic': 'Impacto Econômico',
    'framework.impact.innovation': 'Capacidade de Inovação',
    'framework.impact.societal': 'Benefícios Sociais',
    'framework.impact.economic1': 'Contribuição para o crescimento do PIB de 1,5-2%',
    'framework.impact.economic2': 'Criação de mais de 50.000 empregos altamente qualificados',
    'framework.impact.economic3': 'Aumento da competitividade nas exportações',
    'framework.impact.innovation1': 'Infraestrutura de P&D expandida',
    'framework.impact.innovation2': 'Transferência de tecnologia aprimorada',
    'framework.impact.innovation3': 'Crescimento em pedidos de patentes',
    'framework.impact.societal1': 'Melhorias na inclusão digital',
    'framework.impact.societal2': 'Ganhos em sustentabilidade ambiental',
    'framework.impact.societal3': 'Entrega aprimorada de serviços públicos',
    'framework.monitoring': 'Estrutura de Monitoramento',
    'framework.annual': 'Relatórios Anuais de Progresso',
    'framework.annual.description': 'Avaliação anual abrangente em relação a métricas e metas-chave.',
    'framework.midterm': 'Revisão de Meio-Termo (2025)',
    'framework.midterm.description': 'Análise profunda do progresso de implementação e potenciais ajustes de estratégia.',
    'framework.final': 'Avaliação Final de Impacto (2030)',
    'framework.final.description': 'Avaliação abrangente de resultados, impactos e lições aprendidas.',
    
    // Reports
    'reports.scheduled': 'Visão Geral Mensal de Financiamento',
    'reports.scheduled.description': 'Relatório mensal automatizado sobre alocação e utilização de financiamento',
    'reports.frequency': 'Frequência:',
    'reports.next': 'Próxima geração:',
    'reports.generated': 'Gerado às',
    'reports.recipients': 'Destinatários:',
    'reports.preview': 'Visualizar',
    'reports.pause': 'Pausar',
    'reports.resume': 'Retomar',
    'reports.delete': 'Excluir',
    'reports.confirm': 'Confirmar',
    'reports.cancel': 'Cancelar'
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');
  
  // Initialize language from localStorage if available
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt')) {
      setLanguage(savedLanguage);
    }
  }, []);
  
  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
