
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://tujvvuqhvjicbcqzmcwq.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1anZ2dXFodmppY2JjcXptY3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTc2MjYsImV4cCI6MjA1ODU3MzYyNn0.JByr4xw9fd6vnZ59Y4MKR07a3MGFqsSJJYSJa2iIWAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
